apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: inkfsh/demo-go-common
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command: 
        - "/producer"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
spec:
  type: NodePort
  selector:
    app: kafka-producer
  ports:
  - port: 5000
    nodePort: 30000
    targetPort: 5000
